a_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("restaurants.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("", views.main, name="main"),
    path("index/", views.index, name="index"),
    path("menu/", views.menu, name="menu"),
    path("create/", views.create, name="create"),
    path("<int:restaurant_pk>/detail/", views.detail, name="detail"),
    path("<int:restaurant_pk>/update/", views.update, name="update"),
    path(
        "<int:restaurant_pk>/update/image_delete/",
        views.image_delete,
        name="image_delete",
    ),
    path("<int:restaurant_pk>/delete/", views.delete, name="delete"),
    path("<int:restaurant_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

reviews/urls.py
from django.urls import path
from . import views


app_name = "reviews"

urlpatterns = [
    path("<int:restaurant_pk>/create/", views.create, name="create"),
    path("<int:review_pk>/<int:restaurant_pk>/detail/", views.detail, name="detail"),
    path("<int:review_pk>/<int:restaurant_pk>/update/", views.update, name="update"),
    path("<int:review_pk>/<int:restaurant_pk>/delete/", views.delete, name="delete"),
    path("<int:review_pk>/<int:restaurant_pk>/like/", views.like, name="like"),
    path("<int:review_pk>/comments/", views.comments, name="comments"),
    path(
        "<int:review_pk>/comments/<int:comment_pk>/update/",
        views.comment_update,
        name="comment_update",
    ),
    path(
        "<int:review_pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
]

reviews/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime, timedelta
from django.utils import timezone
from django.template.defaultfilters import slugify


class Review(models.Model):
    restaurants = models.ForeignKey("restaurants.Restaurants", on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_reviews")
    grade = models.FloatField(
        default=1, validators=[MaxValueValidator(5), MinValueValidator(0)]
    )
    # object 를 Post 의 title 문자열로 반환
    def __str__(self):
        return self.title

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return "방금 전"
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + "분 전"
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + "시간 전"
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + "일 전"
        else:
            return False


# image file naming
# instance => 현재 정의된 모델의 인스턴스
# filename => 파일에 원래 제공된 파일 이름. 이것은 최종 목적지 경로를 결정할 때 고려되거나 고려되지 않을 수 있음
def get_image_filename(instance, filename):
    # 해당 Post 모델의 title 을 가져옴
    # title = instance.post.title
    # slug - 의미있는 url 사용을 위한 필드.
    # slugfy 를 사용해서 title을 slug 시켜줌.
    slug = slugify("title")
    # 제목 - 슬러그된 파일이름 형태
    return "post_images/%s-%s" % (slug, filename)


class ReviewImages(models.Model):
    review = models.ForeignKey(
        Review, default=None, on_delete=models.CASCADE, related_name="image"
    )
    image = models.ImageField(upload_to=get_image_filename, blank=True)
    # admin 에서 모델이름
    class Meta:
        # 단수
        verbose_name = "Image"
        # 복수
        verbose_name_plural = "Images"

    # 이것도 역시 post title 로 반환
    def __str__(self):
        return str(self.post)


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=150)

reviews/forms.py
from .models import Review, Comment, ReviewImages
from django import forms
from django.utils.translation import gettext_lazy as _


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            # "title",
            "content",
            # "image",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "주문하신 메뉴는 어떠셨나요? 식당의 분위기와 서비스도 궁금해요!",
                }
            ),
        }
        labels = {
            # "title": "제목",
            "content": "",
            # "image": "",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]


class ReviewImageForm(forms.ModelForm):
    class Meta:
        model = ReviewImages
        fields = ("image",)
        labels = {
            "image": _("Image"),
        }

reviews/views.py
from urllib import request
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review, Comment, ReviewImages
from .forms import CommentForm, ReviewForm, ReviewImageForm
from django.contrib.auth.decorators import login_required
from restaurants.models import Restaurants
from rest_framework.viewsets import ModelViewSet
from .serializers import ReviewSerializer
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect, JsonResponse

# Create your views here.


def create(request, restaurant_pk):
    ImageFormSet = modelformset_factory(ReviewImages, form=ReviewImageForm, extra=5)
    restaurant = Restaurants.objects.get(pk=restaurant_pk)
    grade_ = request.POST.get("grade")
    grade = 0
    if grade_ == "5":
        grade = 5
    elif grade_ == "3":
        grade = 3
    elif grade_ == "1":
        grade = 1
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        formset = ImageFormSet(
            request.POST, request.FILES, queryset=ReviewImages.objects.none()
        )
        if review_form.is_valid() and formset.is_valid():
            review = review_form.save(commit=False)
            review.restaurants = restaurant
            review.user = request.user
            review.grade = grade
            review.save()
            for form in formset.cleaned_data:
                if form:
                    # image file
                    image = form["image"]
                    # review, image file save
                    photo = ReviewImages(review=review, image=image)
                    photo.save()
            # index url 로 요청보냄
            return redirect("restaurants:detail", restaurant.pk)
            # return HttpResponseRedirect("/")
        else:
            print(review_form.errors, formset.errors)
    else:
        review_form = ReviewForm()
        formset = ImageFormSet(queryset=ReviewImages.objects.none())
    context = {
        "name": restaurant.restaurant_name,
        "review_form": review_form,
        "restaurant": restaurant,
        "formset": formset,
    }
    return render(request, "reviews/create.html", context)


class ReviewViewSet(ModelViewSet):
    queryset = Review.objects.all()
    serializer_class = ReviewSerializer


def update(request, restaurant_pk, review_pk):
    review = Review.objects.get(pk=review_pk)
    restaurant = Restaurants.objects.get(pk=restaurant_pk)
    if request.method == "POST":
        review_form = ReviewForm(request.POST, request.FILES, instance=review)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.restaurants = restaurant
            review.user = request.user
            review.save()
            return redirect("restaurants:detail", restaurant.pk)
    else:
        review_form = ReviewForm(instance=review)
    context = {
        "review_form": review_form,
    }
    return render(request, "reviews/update.html", context)


def detail(request, review_pk, restaurant_pk):
    review = Review.objects.get(pk=review_pk)
    restaurant = Restaurants.objects.get(pk=restaurant_pk)
    context = {
        "review": review,
        "restaurant": restaurant,
    }
    return render(request, "reviews/detail.html", context)  # ! 여기 수정 필요!!!!!!


def delete(request, review_pk, restaurant_pk):
    review = Review.objects.get(pk=review_pk)
    restaurant = Restaurants.objects.get(pk=restaurant_pk)
    if request.user.is_authenticated:
        if request.user == review.user:
            review.delete()
            return redirect("restaurants:detail", restaurant.pk)
    return redirect("reviews:detail", review.pk)


@login_required
def like(request, review_pk, restaurant_pk):
    restaurant = Restaurants.objects.get(pk=restaurant_pk)
    review = Review.objects.get(pk=review_pk)
    if review.like.filter(pk=request.user.pk).exists():
        review.like.remove(request.user)
        is_like = False
    else:
        review.like.add(request.user)
        is_like = True
    context = {
        "is_like": is_like,
        "liketCount": review.like.count(),
    }
    return JsonResponse(context)


@login_required
def comments(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment_review = comment_form.save(commit=False)
            comment_review.review = review
            comment_review.user = request.user
            comment_review.save()
    context = {
        "comment_review_content": comment_review.content,
        "comment_review_user": comment_review.user.username,
        "comment_review_pk": comment_review.pk,
    }
    return JsonResponse(context)


@login_required
def comment_update(request, review_pk, comment_pk):
    review = Review.objects.get(pk=review_pk)
    comment = Comment.objects.get(pk=comment_pk)

    if request.user != comment.user:
        return redirect("restaurants:detail", review.pk)

    if request.method == "POST":
        update_comment = request.POST.get("update_comment")
        comment.content = update_comment
        # comment.review = review
        comment.save()
    return redirect("restaurants:detail", review.pk)


@login_required
def comment_delete(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user != comment.user:
        return redirect("restaurants:detail", review_pk)
    if request.method == "POST":
        comment.delete()
    context = {}
    return JsonResponse(context)

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'reviews/css/style_create.css' %}">
{% endblock css %}
{% block content %}
  <div class="container">
    <div class="title">
      <p>
        <span class="r_name">
          <b>{{ name }}</b>
        </span>에 대해 어떻게 생각하세요?
      </p>
    </div>
    <form class="form-form" action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <!--{% bootstrap_form review_form %}-->
      <div class="review_content">{{review_form.title}}</div>
      <div class="review_content">{{review_form.content}}</div>
      <select class="form-select" size="3" aria-label="size 3 select example" name="grade" required="required">
        <option selected="selected">맛 평가를 해 주세요~</option>
        <option value="5">맛있어요</option>
        <option value="3">괜찮아요</option>
        <option value="1">별루에요ㅠ</option>
      </select>
      {{ formset.management_form }}
      <div class="d-flex">
        {% for form in formset %}
          <div class="review_img me-3">
            {{ form }}
              <img src="https://cdn-icons-png.flaticon.com/512/3524/3524388.png" alt="사진 첨부">
            </div>
          {% endfor %}
        </div>
        <div class="review_buttons">
          <button type="button" class="cancel" onclick="location.href='{% url 'restaurants:detail' restaurant.pk%}'">취소</button>
          <button type="submit" class="confirm">리뷰 올리기</button>
        </div>
      </form>
    </div>
  {% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

  <div class="row justify-content-between p-3" style="background-color:lightgrey; height: 300px;">
    <div class="d-flex justify-content-between p-0 h-auto">
      <div class="d-flex">
        <div class="rounded-pill" style="background-color:yellow">프로필사진</div>
        <div class="rounded-pill" style="background-color:yellow">맛있다</div>
      </div>

      <div class="rounded-pill" style="background-color:yellow">{{ review.created_at }}</div>
    </div>
    <div style="background-color:grey;" class="p-0 h-75">{{ review.content }}</div>
  </div>
  {% if request.user == review.user %}
    <button type="submit" class="btn btn-outline-dark" onclick="location.href='{% url 'reviews:update' review.pk restaurant.pk%}'">수정</button>
    <form action="{% url 'reviews:delete' review.pk restaurant.pk%}" method="POST">
      {% csrf_token %}
      <input type="submit" class='btn btn-dark' value='삭제'>
    </form>
  {% else %}
  {% endif %}
{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>Update</h1>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form review_form %}
    <button type="submit" class="btn btn-outline-dark">생성</button>
  </form>
{% endblock content %}