a_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("restaurants.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("", views.main, name="main"),
    path("index/", views.index, name="index"),
    path("menu/", views.menu, name="menu"),
    path("create/", views.create, name="create"),
    path("<int:restaurant_pk>/detail/", views.detail, name="detail"),
    path("<int:restaurant_pk>/update/", views.update, name="update"),
    path(
        "<int:restaurant_pk>/update/image_delete/",
        views.image_delete,
        name="image_delete",
    ),
    path("<int:restaurant_pk>/delete/", views.delete, name="delete"),
    path("<int:restaurant_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

restaurants/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from django.template.defaultfilters import slugify

category_CHOICES = (
    ('한식', '한식'),
    ('양식', '양식'),
    ('중식', '중식'),
    ('일식', '일식'),
    ('기타', '기타'),
)

parking_CHOICES = (
    ('주차공간없음', '주차공간없음'),
    ('유료주차 가능', '유료주차 가능'),
    ('무료주차 가능', '무료주차 가능'),
    ('기타', '기타'),
)

price_avg_CHOICES = (
    ('만원 미만', '만원 미만'),
    ('1만원-2만원', '1만원-2만원'),
    ('2만원-3만원', '2만원-3만원'),
    ('3만원-5만원', '3만원-5만원'),
    ('5만원 이상', '5만원 이상'),
)

# Create your models here.
class Restaurants(models.Model):
    restaurant_name = models.CharField(max_length=50)
    전화번호 = PhoneNumberField(blank=True)
    address = models.TextField()
    Opening_hours = models.TextField()
    menu = models.TextField()
    day_off = models.CharField(max_length=40)
    price_avg = models.CharField(max_length=50, choices=price_avg_CHOICES)
    parking = models.CharField(max_length=50, choices=parking_CHOICES)
    category = models.CharField(max_length=50, choices=category_CHOICES)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_restaurant"
    )
    hits = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        blank = True,
        processors = [Thumbnail(300, 300)],
        format = 'JPEG',
        options = {'quality': 90},
    )

    @property
    def click(self):
        self.hits += 1
        self.save()


class Search(models.Model):
    keyword = models.TextField(max_length=30)
    count = models.IntegerField(default=0)


def get_image_filename(instance, filename):
    slugs = slugify("title")
    # 제목 - 슬러그된 파일이름 형태
    return "post_images/%s-%s" % (slugs, filename)

class RestaurantImages(models.Model):
    restaurant = models.ForeignKey(
        Restaurants, default=None, on_delete=models.CASCADE, related_name="restaurant"
    )
    image = models.ImageField(upload_to=get_image_filename, blank=True)
    class Meta:
        # 단수
        verbose_name = "Image"
        # 복수
        verbose_name_plural = "Images"

restaurants/forms.py
from django import forms
from .models import Restaurants
from phonenumber_field.formfields import PhoneNumberField
from .models import RestaurantImages
from django.utils.translation import gettext_lazy as _


class RestaurantForm(forms.ModelForm):
    전화번호 = PhoneNumberField(
        region="KR",
        required=False,
    )

    class Meta:
        model = Restaurants
        fields = "__all__"
        widgets = {
            "menu": forms.Textarea(
                attrs={
                    "placeholder": "메뉴 - 가격, 형식으로 적어주세요. 예시) 탕수육(소) - 10000원, 탕수육(중) - 20000원, 탕수육(대) - 30000원",
                }
            ),
        }
        exclude = ["like_users", "user", "hits", "address"]
        labels = {
            "restaurant_name": "음식점명",
            "Opening_hours": "영업시간",
            "menu": "메뉴",
            "price_avg": "가격대",
            "parking": "주차",
            "day_off": "휴일",
            "category": "카테고리",
            "image": "가게 썸네일",
        }


class RestaurantImageForm(forms.ModelForm):
    class Meta:
        model = RestaurantImages
        fields = ("image",)
        labels = {
            "image": _("Image"),
        }

restaurants/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import (
    require_safe,
    require_http_methods,
    require_POST,
)
from django.contrib.auth.decorators import login_required
from .models import Restaurants, Search, RestaurantImages
from .forms import RestaurantForm, RestaurantImageForm
from django.contrib import messages
from reviews.models import Review
from django.db.models import Q
from datetime import datetime
from django.core.paginator import Paginator
from reviews.forms import CommentForm
from django.http import JsonResponse
from django.forms import modelformset_factory
from dotenv import load_dotenv
import os


# Create your views here.
def main(request):
    s = Search.objects.filter().order_by("-count")[:3]
    m = Search.objects.filter().order_by("count")[1:12]
    context = {
        "s": s,
        "m": m,
    }
    return render(request, "restaurants/main.html", context)


def index(request):
    restaurants = Restaurants.objects.all()
    context = {
        "restaurants": restaurants,
    }
    return render(request, "restaurants/index.html", context)


def detail(request, restaurant_pk):
    load_dotenv()
    JSMAPKEY = os.getenv("JSMAPKEY")
    restaurant = get_object_or_404(Restaurants, pk=restaurant_pk)
    # 메뉴를 - 와 , 기준으로 분리하는 작업
    aa = restaurant.menu.split(",")
    bbb = []
    restaurant_menu = []
    for a in aa:
        bbb.append(a.split("-"))
    for bb in bbb:
        for b in bb:
            restaurant_menu.append(b.strip())
    restaurant_menu_left = []
    restaurant_menu_right = []
    for i in range(len(restaurant_menu)):
        if (i % 2) == 0:
            restaurant_menu_left.append(restaurant_menu[i])
        else:
            restaurant_menu_right.append(restaurant_menu[i])
    reviews = restaurant.review_set.all()
    page = request.GET.get("page", "1")
    paginator = Paginator(reviews, 3)
    page_obj = paginator.get_page(page)
    comment_form = CommentForm()
    cnt = 0
    add = 0
    for review in reviews:
        cnt += 1
        add += review.grade
    if cnt == 0:
        grade = ""
    else:
        grade = round(add / cnt, 1)
    context = {
        "restaurant": restaurant,
        "grade": grade,
        "question_list": page_obj,
        "comment_form": comment_form,
        "JSMAPKEY": JSMAPKEY,
        "restaurant_menu_left": restaurant_menu_left,
        "restaurant_menu_right": restaurant_menu_right,
    }
    return render(request, "restaurants/detail.html", context)


def menu(request):
    category = request.GET.get("category")
    restaurants = Restaurants.objects.filter(category=category)
    context = {
        "category": category,
        "restaurants": restaurants,
    }
    return render(request, "restaurants/menu.html", context)


@login_required
@require_http_methods(["GET", "POST"])
def create(request):
    ImageFormSet = modelformset_factory(
        RestaurantImages, form=RestaurantImageForm, extra=8
    )
    if request.method == "POST":
        form = RestaurantForm(request.POST, request.FILES)
        address = request.POST.get("address")
        formset = ImageFormSet(
            request.POST, request.FILES, queryset=RestaurantImages.objects.none()
        )
        if form.is_valid() and formset.is_valid():
            restaurant = form.save(commit=False)
            restaurant.address = address
            restaurant.user = request.user
            restaurant.save()
            for forms in formset.cleaned_data:
                if forms:
                    image = forms["image"]
                    photo = RestaurantImages(restaurant=restaurant, image=image)
                    photo.save()
            messages.success(request, "글 작성이 완료되었습니다.")
            return redirect("restaurants:main")
        else:
            print(form.errors, formset.errors)
    else:
        form = RestaurantForm()
        formset = ImageFormSet(queryset=RestaurantImages.objects.none())
    context = {
        "form": form,
        "formset": formset,
    }
    return render(request, "restaurants/forms.html", context)

@login_required
@require_http_methods(["GET", "POST"])
def update(request, restaurant_pk):
    restaurant = get_object_or_404(Restaurants, pk=restaurant_pk)
    ImageFormSet = modelformset_factory(
        RestaurantImages, form=RestaurantImageForm, extra=8
    )
    if request.method == "POST":
        form = RestaurantForm(request.POST, request.FILES, instance=restaurant)
        address = request.POST.get("address")
        formset = ImageFormSet(
            request.POST,
            request.FILES,
            queryset=RestaurantImages.objects.none(),
        )
        if form.is_valid() and formset.is_valid():
            restaurant_ = form.save(commit=False)
            restaurant_.address = address
            restaurant_.user = request.user
            restaurant_.save()
            for forms in formset.cleaned_data:
                if forms:
                    image = forms["image"]
                    photo = RestaurantImages(restaurant=restaurant, image=image)
                    photo.save()
            messages.success(request, "글 작성이 완료되었습니다.")
            return redirect("restaurants:detail", restaurant.pk)
        else:
            print(form.errors, formset.errors)
    else:
        form = RestaurantForm(instance=restaurant)
        address_ = restaurant.address
        formset = ImageFormSet(
            queryset=RestaurantImages.objects.none(),
        )
    context = {
        "restaurant": restaurant,
        "form": form,
        "formset": formset,
        "address_": address_,
    }
    return render(request, "restaurants/forms.html", context)


@login_required
def image_delete(request, restaurant_pk):
    restaurant = Restaurants.objects.get(pk=restaurant_pk)
    images = restaurant.restaurant.all()
    for image in images:
        image.delete()
    return redirect("restaurants:update", restaurant.pk)


@login_required
def delete(request, restaurant_pk):
    get_object_or_404(Restaurants, pk=restaurant_pk).delete()
    return redirect("restaurants:main")


@login_required
def like(request, restaurant_pk):
    restaurant = get_object_or_404(Restaurants, pk=restaurant_pk)
    if restaurant.like_users.filter(pk=request.user.pk).exists():
        restaurant.like_users.remove(request.user)
        is_like = False
    else:
        restaurant.like_users.add(request.user)
        is_like = True
    context = {
        "isLiked": is_like,
        "likeCount": restaurant.like_users.count(),
    }
    return JsonResponse(context)


def search(request):
    s = Search.objects.filter().order_by("count")[1:12]
    if request.method == "GET":
        content_list = Restaurants.objects.all()
        search = request.GET.get("search", "")

        if len(search) >= 0:
            if Search.objects.filter(keyword=search).exists():
                search_keyword = Search.objects.get(keyword=search)
                search_keyword.count += 1
                search_keyword.save()
            else:
                Search.objects.create(keyword=search, count=1)

        if search:
            search_lists = content_list.filter(
                Q(restaurant_name__icontains=search)
                | Q(menu__icontains=search)
                | Q(category__icontains=search)
                | Q(price_avg=search)
            )
            context = {
                "search_lists": search_lists,
                "s": s,
                "search": search,
            }
            return render(request, "restaurants/search.html", context)

restaurants/templates/restaurants/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'restaurants/css/index.css' %}">
{% endblock css %}

{% block content %}
  <div class="container mt-0">
    {% for restaurant in restaurants %}
      <div class="a_restaurant">
        <div class="direction">
          <img src="https://cdn-icons-png.flaticon.com/512/5582/5582962.png" alt="위치 아이콘">
          <p>{{ restaurant.address }}</p>
        </div>
        <div class="r_img">
          {% if restaurant.image %}
            <img src="{{ restaurant.image.url }}" alt="음식점 썸네일 사진">
          {% else %}
            <img src="https://www.dummyimage.com/300X300/000/fff"/>
          {% endif %}
        </div>
        <div class="hash">
          <form action="{% url 'restaurants:menu' %}">
            <button type="submit" class="a_menu">
              <p>#{{ restaurant.category }}</p>
              <input type="text" value="{{ restaurant.category }}" class="category-value" name="category">
            </button>
          </form>
          <form action="{% url 'restaurants:search' %}">
            <button type="submit" class="a_menu">
              <p>#{{ restaurant.price_avg }}</p>
              <input type="search" value="{{ restaurant.price_avg }}" name="search" aria-label="Search" id="search" class="category-value"/>
            </button>
          </form>

          <button type="submit" class="a_menu">
            <p>#{{ restaurant.parking }}</p>

          </button>

        </div>
        <div class="info_text">
          <p class="name">
            <a href="{% url 'restaurants:detail' restaurant.pk %}">{{ restaurant.restaurant_name }}</a>
          </p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

restaurants/templates/restaurants/main.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'restaurants/css/main.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
  <!-- 상단 -->
  <div class="upper">
    <!--<p>솔직한 맛 평가</p>-->
    <p>솔직한 맛을 담은</p>
    <h1>오늘의 플레이트</h1>
  </div>

  <!-- 배너 -->
  <di class="row">
    <div class="col-9 px-1"><img src="{% static 'restaurants/img/main.jpg' %}" alt="" style="width: 100%;height:100%">
    </div>
    <div class="col-3 px-1">
      <div class="pb-2"><img src="{% static 'restaurants/img/main_side(1).jpg' %}" class="img-fluid" alt=""></div>
      <div class="pb-2"><img src="{% static 'restaurants/img/main_side(2).jpg' %}" class="img-fluid" alt=""></div>
      <div><img src="{% static 'restaurants/img/main_side(3).jpg' %}" class="img-fluid" alt=""></div>
    </div>
  </di>


  <!-- 인기 검색어 -->
  <div class="search_popular">
    <div class="popular_title">인기검색어</div>
    {% for w in s %}
    <div class="popular_word">
      <span class="hash_mark">#</span>
      <label for="search" class="css-xd55zv e1387oiq0" id="{{w.pk}}">{{ w.keyword }}</label>
    </div>
    {% endfor %}
  </div>


  <!--검색-->
  <form class="search" action="{% url 'restaurants:search' %}">
    <input class="input_form" type="search" placeholder="식당, 카테고리" name="search" aria-label="Search" id="search"
      required>
    <button class="button" type="submit"><img src="https://cdn-icons-png.flaticon.com/512/16/16492.png"
        alt="검색 아이콘"></button>
  </form>

  <!-- 카테고리 -->
  <p class="cate_p">오늘 먹을 음식은</p>
  <div class="food_cate">
    <form action="{% url 'restaurants:menu' %}">
      <button type="submit" class="a_menu">
        <img src="https://cdn-icons-png.flaticon.com/512/4480/4480784.png" alt="한식 카테고리">
        <p>한식</p>
        <input type="text" value="한식" class="category-value" name="category">
      </button>
    </form>
    <form action="{% url 'restaurants:menu' %}">
      <button type="submit" class="a_menu">
        <img src="https://cdn-icons-png.flaticon.com/512/3511/3511307.png" alt="양식 카테고리">
        <p>양식</p>
        <input type="text" value="양식" class="category-value" name="category">
      </button>
    </form>
    <form action="{% url 'restaurants:menu' %}">
      <button type="submit" class="a_menu">
        <img src="https://cdn-icons-png.flaticon.com/512/2548/2548242.png" alt="중식 카테고리">
        <p>중식</p>
        <input type="text" value="중식" class="category-value" name="category">
      </button>
    </form>
    <form action="{% url 'restaurants:menu' %}">
      <button type="submit" class="a_menu">
        <img src="https://cdn-icons-png.flaticon.com/512/5391/5391971.png" alt="일식 카테고리">
        <p>일식</p>
        <input type="text" value="일식" class="category-value" name="category">
      </button>
    </form>
    <form action="{% url 'restaurants:menu' %}">
      <button type="submit" class="a_menu">
        <img src="https://cdn-icons-png.flaticon.com/512/7688/7688778.png" alt="기타 카테고리">
        <p>기타</p>
        <input type="text" value="기타" class="category-value" name="category">
      </button>
    </form>
  </div>

  <!--음식 그림-->
  <div class="random_menu">
    <div class="menu_p">
      <p>어떤 음식을 먹을지 고민 될 땐</p>

      <!--음식 섞기 -->
      <button id="shuffle-menu" class="random_button" type="button"><img
          src="https://cdn-icons-png.flaticon.com/512/2102/2102198.png" alt="랜덤 아이콘"></button>
      {% comment %}
      <script src="{% static 'restaurants/js/main.js' %}"></script>
      {% endcomment %}
    </div>
    <!-- 지역선택 -->
    <div class="random_food" id="random-food">
    </div>
  </div>


  <!-- 자바스크립트 -->
  <!-- 랜덤 음식 -->
  <script>
    const row = document.querySelector("#random-food");
    var foodsList = ["떡볶이.jpg", "삼겹살.jpg", "치킨.png", "피자.jpg", "김밥.jpg", '비빔밥.jpg', '죽.jpg', '칼국수.jpg', '물냉면.jpg', '짜장면.jpg', '짬뽕.jpg', '떡갈비.jpg', '갈비찜.jpg', '해물찜.jpg', '계란말이.jpg', '순대국.jpg', '감자탕.jpg',];
    temp(0);

    function temp(num) {
      var template = [];
      for (let i = 0; i < 5; i++) {
        var a = foodsList[(i + num) % foodsList.length];
        var url = "{% static 'restaurants/img/change' %}".replace("change", a);
        template.push(`<div class="col text-center"><img src="${url}" alt="" class="img-fluid"></div>`);
        row.insertAdjacentHTML("beforeend", template[i]);
      }
    }

    const shuffleMenu = document.querySelector("#shuffle-menu");
    shuffleMenu.addEventListener("click", () => {
      row.innerHTML = "";
      temp(Math.floor(Math.random() * (foodsList.length - 1 - 0) + 1));
    });
  </script>

  <!-- 캐러셀 -->
  <script>
    document.querySelector('.slide-2').addEventListener('click', () => {
      document.querySelector('.slide-container').style.transform = 'translateX(-100vw)'
      document.querySelector('.slide-2').classList.add('active')
      document.querySelector('.slide-1').classList.remove('active')
      document.querySelector('.slide-3').classList.remove('active')
    })
    document.querySelector('.slide-3').addEventListener('click', () => {
      document.querySelector('.slide-container').style.transform = 'translateX(-200vw)'
      document.querySelector('.slide-3').classList.add('active')
      document.querySelector('.slide-1').classList.remove('active')
      document.querySelector('.slide-2').classList.remove('active')
    })
    document.querySelector('.slide-1').addEventListener('click', () => {
      document.querySelector('.slide-container').style.transform = 'translateX(0vw)'
      document.querySelector('.slide-1').classList.add('active')
      document.querySelector('.slide-2').classList.remove('active')
      document.querySelector('.slide-3').classList.remove('active')
    })
  </script>

  <!-- 인기검색어 클릭 -->
  <script>
    const populars = document.querySelectorAll('.e1387oiq0');
    populars.forEach((el) => {
      el.addEventListener('click', (e) => {
        document.querySelector('#search').value = e.currentTarget.innerText
      })
    })
  </script>
</div>
{% endblock content %}







<!-- 캐러셀 실패작 -->
<!--{% comment %}
<script>
  var start = 0
  var clicking = false
  var slideBox = document.querySelectorAll('.slide-box')

  SlideBox(0)
  SlideBox(1)
  SlideBox(2)

  function SlideBox(num) {
    SlideBoxMouseDown(num)
    SlideBoxMouseMove(num)
    SlideBoxMouseUp(num)
  }

  function SlideBoxMouseDown(num) {
    slideBox[num].addEventListener('mousedown', (e) => {
      start = e.screenX
      clicking = true
    })
  }
  function SlideBoxMouseMove(num) {
    slideBox[num].addEventListener('mousemove', (e) => {
      if (clicking == true) {
        document.querySelector('.slide-container').style.transform = `translateX(${(-1) * (num * 100) + e.screenX - start}px)`
      }
    })
  }
  function SlideBoxMouseUp(num) {
    slideBox[num].addEventListener('mouseup', (e) => {
      clicking = false
      if (e.clientX - start < -100) {
        document.querySelector('.slide-container').style.transform = `translateX(-${((num + 1) * 100) % 300}vw)`
        document.querySelector('.slide-container').style.transition = 'all 0.5s'
      } else {
        document.querySelector('.slide-container').style.transform = `translateX(-${(num * 100) % 300}vw)`
        document.querySelector('.slide-container').style.transition = 'all 0.5s'
      }
      setTimeout(() => {
        document.querySelector('.slide-container').style.transition = 'none'
      }, 500)
    })
  }
    
  </scrip > {% endcomment %}-->

restaurants/templates/restaurants/menu.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'restaurants/css/menu.css' %}">
{% endblock css %}
{% block content %}
  <container>
    <div class="food_cate">
      <form action="{% url 'restaurants:menu' %}">
        <button type="submit" class="a_menu">
          <img src="https://cdn-icons-png.flaticon.com/512/4480/4480784.png" alt="한식 카테고리">
          <p>한식</p>
          <input type="text" value="한식" class="category-value" name="category">
        </button>
      </form>
      <form action="{% url 'restaurants:menu' %}">
        <button type="submit" class="a_menu">
          <img src="https://cdn-icons-png.flaticon.com/512/3511/3511307.png" alt="양식 카테고리">
          <p>양식</p>
          <input type="text" value="양식" class="category-value" name="category">
        </button>
      </form>
      <form action="{% url 'restaurants:menu' %}">
        <button type="submit" class="a_menu">
          <img src="https://cdn-icons-png.flaticon.com/512/2548/2548242.png" alt="중식 카테고리">
          <p>중식</p>
          <input type="text" value="중식" class="category-value" name="category">
        </button>
      </form>
      <form action="{% url 'restaurants:menu' %}">
        <button type="submit" class="a_menu">
          <img src="https://cdn-icons-png.flaticon.com/512/5391/5391971.png" alt="일식 카테고리">
          <p>일식</p>
          <input type="text" value="일식" class="category-value" name="category">
        </button>
      </form>
      <form action="{% url 'restaurants:menu' %}">
        <button type="submit" class="a_menu">
          <img src="https://cdn-icons-png.flaticon.com/512/7688/7688778.png" alt="기타 카테고리">
          <p>기타</p>
          <input type="text" value="기타" class="category-value" name="category">
        </button>
      </form>
    </div>

    <h2>{{ category }}</h2>
    <div class="restaurants">
      {% for restaurant in restaurants %}
        <a href="{% url 'restaurants:detail' restaurant.pk %}">
          <div class="img-text-box">
            <p id="img-text">
              {{ restaurant.restaurant_name }}
            </p>
            {% if restaurant.image %}
              <img src="{{ restaurant.image.url }}" alt="음식점의 음식 사진">
            {% else %}
              <img src="https://www.dummyimage.com/300X300/000/fff"/>
            {% endif %}
          </div>
        </a>
      {% endfor %}
    </div>
    {% comment %} <div class="more">
      <button type="button">더보기</button>
    </div> {% endcomment %}
  </container>
{% endblock %}

restaurants/templates/restaurants/search.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'restaurants/css/search.css' %}">
{% endblock css %}
{% block content %}
<div class= "col-3 my-2 p-1 border border-2 border-warning rounded">
  <h5>검색어 :
    {{ search }}</h5>
    최근 검색어 : {% for h in s %}
    <span style="background-color: #ffeb7c; color: black;"  class="badge">#{{ h.keyword }}</span>
  {% endfor %}
</div>
  <div class="container">
    {% for restaurant in search_lists %}
      <div class="a_restaurant">
        <div class="direction">
          <img src="https://cdn-icons-png.flaticon.com/512/4519/4519622.png" alt="위치 아이콘">
          <p>{{ restaurant.address }}</p>
        </div>
        <div class="r_img">
          {% if restaurant.image %}
            <img src="{{ restaurant.image.url }}" alt="음식점의 음식 사진">
          {% else %}
            <img src="https://www.dummyimage.com/300X300/000/fff"/>
          {% endif %}
        </div>
        <!-- 실제 해시로 변경 -->
        <div class="hash">
          <form action="{% url 'restaurants:menu' %}">
            <button type="submit" class="a_menu">
              <p>#{{ restaurant.category }}</p>
              <input type="text" value="{{ restaurant.category }}" class="category-value" name="category">
            </button>
          </form>
          <form action="{% url 'restaurants:search' %}">
            <button type="submit" class="a_menu">
              <p>#{{ restaurant.price_avg }}</p>
              <input type="search" value="{{ restaurant.price_avg }}" name="search" aria-label="Search" id="search" class="category-value"/>
            </button>
          </form>
          <form action="{% url 'restaurants:search' %}">
            <button type="submit" class="a_menu">
              <p>#{{ restaurant.parking }}</p>
              <input type="search" value="{{ restaurant.parking }}" name="search" aria-label="Search" id="search" class="category-value"/>
            </button>
          </form>
        </div>
        <div class="info_text">
          <p class="name">
            <a href="{% url 'restaurants:detail' restaurant.pk %}">{{ restaurant.restaurant_name }}</a>
          </p>
          <!--<p class="total_view">3,234 view</p>-->
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}