a_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("restaurants.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("delete/", views.delete, name="user_delete"),
    path("update/", views.update, name="update"),
    path("profile/", views.profile, name="profile"),
    path("password/", views.change_password, name="change_password"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
]

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("", views.main, name="main"),
    path("index/", views.index, name="index"),
    path("menu/", views.menu, name="menu"),
    path("create/", views.create, name="create"),
    path("<int:restaurant_pk>/detail/", views.detail, name="detail"),
    path("<int:restaurant_pk>/update/", views.update, name="update"),
    path(
        "<int:restaurant_pk>/update/image_delete/",
        views.image_delete,
        name="image_delete",
    ),
    path("<int:restaurant_pk>/delete/", views.delete, name="delete"),
    path("<int:restaurant_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail


class User(AbstractUser):
    image = ProcessedImageField(
        blank=True,
        processors=[Thumbnail(200, 300)],
        format="JPEG",
        options={"quality": 90},
    )
    followings = models.ManyToManyField(
        "self",
        symmetrical=False,
        related_name="followers",
    )

restaurants/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField
from django.template.defaultfilters import slugify

category_CHOICES = (
    ('한식', '한식'),
    ('양식', '양식'),
    ('중식', '중식'),
    ('일식', '일식'),
    ('기타', '기타'),
)

parking_CHOICES = (
    ('주차공간없음', '주차공간없음'),
    ('유료주차 가능', '유료주차 가능'),
    ('무료주차 가능', '무료주차 가능'),
    ('기타', '기타'),
)

price_avg_CHOICES = (
    ('만원 미만', '만원 미만'),
    ('1만원-2만원', '1만원-2만원'),
    ('2만원-3만원', '2만원-3만원'),
    ('3만원-5만원', '3만원-5만원'),
    ('5만원 이상', '5만원 이상'),
)

# Create your models here.
class Restaurants(models.Model):
    restaurant_name = models.CharField(max_length=50)
    전화번호 = PhoneNumberField(blank=True)
    address = models.TextField()
    Opening_hours = models.TextField()
    menu = models.TextField()
    day_off = models.CharField(max_length=40)
    price_avg = models.CharField(max_length=50, choices=price_avg_CHOICES)
    parking = models.CharField(max_length=50, choices=parking_CHOICES)
    category = models.CharField(max_length=50, choices=category_CHOICES)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_restaurant"
    )
    hits = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = ProcessedImageField(
        blank = True,
        processors = [Thumbnail(300, 300)],
        format = 'JPEG',
        options = {'quality': 90},
    )

    @property
    def click(self):
        self.hits += 1
        self.save()


class Search(models.Model):
    keyword = models.TextField(max_length=30)
    count = models.IntegerField(default=0)


def get_image_filename(instance, filename):
    slugs = slugify("title")
    # 제목 - 슬러그된 파일이름 형태
    return "post_images/%s-%s" % (slugs, filename)

class RestaurantImages(models.Model):
    restaurant = models.ForeignKey(
        Restaurants, default=None, on_delete=models.CASCADE, related_name="restaurant"
    )
    image = models.ImageField(upload_to=get_image_filename, blank=True)
    class Meta:
        # 단수
        verbose_name = "Image"
        # 복수
        verbose_name_plural = "Images"

reviews/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime, timedelta
from django.utils import timezone
from django.template.defaultfilters import slugify


class Review(models.Model):
    restaurants = models.ForeignKey("restaurants.Restaurants", on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_reviews")
    grade = models.FloatField(
        default=1, validators=[MaxValueValidator(5), MinValueValidator(0)]
    )
    # object 를 Post 의 title 문자열로 반환
    def __str__(self):
        return self.title

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.created_at

        if time < timedelta(minutes=1):
            return "방금 전"
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + "분 전"
        elif time < timedelta(days=1):
            return str(int(time.seconds / 3600)) + "시간 전"
        elif time < timedelta(days=7):
            time = datetime.now(tz=timezone.utc).date() - self.created_at.date()
            return str(time.days) + "일 전"
        else:
            return False


# image file naming
# instance => 현재 정의된 모델의 인스턴스
# filename => 파일에 원래 제공된 파일 이름. 이것은 최종 목적지 경로를 결정할 때 고려되거나 고려되지 않을 수 있음
def get_image_filename(instance, filename):
    # 해당 Post 모델의 title 을 가져옴
    # title = instance.post.title
    # slug - 의미있는 url 사용을 위한 필드.
    # slugfy 를 사용해서 title을 slug 시켜줌.
    slug = slugify("title")
    # 제목 - 슬러그된 파일이름 형태
    return "post_images/%s-%s" % (slug, filename)


class ReviewImages(models.Model):
    review = models.ForeignKey(
        Review, default=None, on_delete=models.CASCADE, related_name="image"
    )
    image = models.ImageField(upload_to=get_image_filename, blank=True)
    # admin 에서 모델이름
    class Meta:
        # 단수
        verbose_name = "Image"
        # 복수
        verbose_name_plural = "Images"

    # 이것도 역시 post title 로 반환
    def __str__(self):
        return str(self.post)


class Comment(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=150)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ("username", "email", "first_name", "last_name")


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ("email", "first_name", "last_name")


class ProfileCustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ("image",)
        label = {
            'image': '프로필',
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import (
    CustomUserCreationForm,
    CustomUserChangeForm,
    ProfileCustomUserChangeForm,
)
from django.contrib.auth.decorators import login_required
from django.contrib import messages


@login_required
def index(request):
    users = get_user_model().objects.all()  # 저장된 모든 User를 가져온다.
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)  # 회원가입과 동시에 로그인을 시키기 위해
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.user.is_authenticated:  # 로그인이 된 상태에서는 로그인 화면에 들어갈 수 없다.
        return redirect("restaurants:main")
    if request.method == "POST":
        form = AuthenticationForm(
            request, data=request.POST
        )  # request가 없어도 잘 돌아가는거 같음 하지만 대부분이 request를 필수적으로 받아 가지고 편의상 넣겠음
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "restaurants:main")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect("accounts:login")

@login_required
def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    like_restaurant = user.like_restaurant.all()
    user_all_reviews = user.review_set.all()
    print(user_all_reviews)
    context = {
        "user": user,
        "like_restaurants": like_restaurant,
        "user_all_reviews": user_all_reviews,
    }
    return render(request, "accounts/detail.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("accounts:login")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "프로필 정보가 성공적으로 변경되었습니다.")
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context=context)

@login_required
def profile(request):
    if request.method == "POST":
        form = ProfileCustomUserChangeForm(
            request.POST, request.FILES, instance=request.user
        )
        if form.is_valid():
            form.save()
            messages.success(request, "프로필사진이 성공적으로 변경되었습니다.")
            return redirect("accounts:detail", request.user.pk)
    else:
        form = ProfileCustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/profile.html", context=context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "비밀번호 변경이 성공적으로 완료되었습니다.")
            messages.warning(request, "새로 로그인해주세요.")
            return redirect("accounts:login")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)


@login_required
def follow(request, user_pk):
    person = get_user_model().objects.get(pk=user_pk)
    if person != request.user:
        if person.followers.filter(pk=request.user.pk).exists():
            # if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
    return redirect("accounts:profile", person.username)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'accounts/css/password.css' %}">
{% endblock css %}

{% block content %}

  <h2 class="title">비밀번호 수정</h2>
  <div class="form">
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="submit">수정</button>
      <button type="button" class="back" onclick="location.href='{% url 'accounts:detail' user.pk %}' ">돌아가기</button>
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'accounts/css/detail.css' %}">
{% endblock css %}

{% block content %}
  <div class="container">
    <h2 class="title">
      <span class="user">{{user}}</span>
      님의 정보</h2>

    <div class="infos">
      <div class="small_info">
        <!-- {{ user.pk }}-->
        <p>
          <span class="name">
            {{ user.last_name }}
            {{ user.first_name }}</span><br>
          {{ user.email }}</p>
      </div>

      <div class="user_buttons">
        {% if request.user.pk == user.pk %}
          <button>
            <a href="{% url 'accounts:profile' %}">프로필<br>사진 설정</a>
          </button>
          <button>
            <a href="{% url 'accounts:update' %}">프로필<br>정보 수정</a>
          </button>
          <button>
            <a href="{% url 'accounts:change_password' %}">비밀번호<br>수정</a>
          </button>
        {% endif %}
      </div>
    </div>

    <hr class="hr">
    <div class="bookmarked">
      <p class="bookmarked_p">북마크한 음식점</p>
      <p class="explanation">*음식점 이름을 누르면 해당 음식점의 자세한 정보를 볼 수 있습니다.</p>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">음식점명</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            <th scope="col">카테고리</th>
          </tr>
        </thead>
        {% for like_restaurant in like_restaurants %}
          <tbody>
            <tr>
              <th scope="row">
                <a href="{% url 'restaurants:detail' like_restaurant.pk %}">
                  {{ like_restaurant.restaurant_name }}</a>
              </th>
              <td>{{ like_restaurant.address }}</td>
              <td>{{ like_restaurant.전화번호 }}</td>
              <td>{{ like_restaurant.category }}</td>
            </tr>
          </tbody>
        {% endfor %}
      </table>
    </div>

    <hr class="hr">
    <div class="restaurant">
      <p class="restaurant_p">등록한 음식점</p>
      <p class="explanation">*음식점 이름을 누르면 해당 음식점의 자세한 정보를 볼 수 있습니다.</p>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">음식점명</th>
            <th scope="col">주소</th>
            <th scope="col">전화번호</th>
            <th scope="col">카테고리</th>
          </tr>
        </thead>
        {% for make_restaurant in user.restaurants_set.all %}
          <tbody>
            <tr>
              <th scope="row">
                <a href="{% url 'restaurants:detail' make_restaurant.pk %}">
                  {{ make_restaurant.restaurant_name }}</a>
              </th>
              <td>{{ make_restaurant.address }}</td>
              <td>{{ make_restaurant.전화번호 }}</td>
              <td>{{ make_restaurant.category }}</td>
            </tr>
          </tbody>
        {% endfor %}
      </table>
    </div>

    <hr class="hr">
    <div class="comments">
      <p class="comments_p">작성한 댓글</p>
      {% for user_all_review in user_all_reviews %}
        <p>
          {{user_all_review.content}}
        </p>
      {% endfor %}
    </div>
  </div>

  <hr class="hr">
  <div class="review">
    <p class="review_p">작성한 대댓글</p>
    {% for comment in user.comment_set.all %}
      <p>
        {{ comment.content }}
      </p>
    {% endfor %}

  {% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>회원 목록</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">user</th>
        <th scope="col">email</th>
        <th scope="col">last_login</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <th scope="row">
            <a href="{% url 'accounts:detail' user.pk %}">{{ user.username}}</a>
          </th>
          <td>{{ user.email}}</td>
          <td>{{ user.last_login}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
  <h2 class="title">어서오세요 :D</h2>
  <div class="form">
    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <div class="d-flex">
        <button type="submit" class="login">로그인</button>
        <button type="button" class="new" onclick="location.href='{% url 'accounts:signup' %}' ">회원가입</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">
{% endblock css %}

{% block content %}
  <h2 class="title">프로필 사진</h2>
  <div class="profile">
    <img src="https://cdn-icons-png.flaticon.com/512/754/754989.png" alt="접시 아이콘">
    <div class="form">
      <form action="" method="POST" enctype="multipart/form-data" id="profile-form">
        {% csrf_token %}
        {{ form.image }}
        <div class="buttons">
          <input type="submit" value="등록" class="submit"/>
          <button type="button" class="back" onclick="location.href='{% url 'accounts:detail' user.pk %}' ">돌아가기</button>
        </div>
      </form>
      <img src="https://cdn-icons-png.flaticon.com/512/3524/3524388.png" alt="사진 추가 아이콘" class="upload_icon">
    </div>
  </div>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
  <h2 class="title">가입을 환영합니다!</h2>
  <div class="form">
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="submit">가입하기</button>
    </form>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'accounts/css/update.css' %}">
{% endblock css %}

{% block content %}
  <h2 class="title">정보 수정</h2>
  <div class="form">
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input class="submit" type="submit" value="수정"/>
      <button type="button" class="back" onclick="location.href='{% url 'accounts:detail' user.pk %}' ">돌아가기</button>
    </form>
  </div>
{% endblock content %}