a_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("restaurants.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>/", views.detail, name="detail"),
    path("delete/", views.delete, name="user_delete"),
    path("update/", views.update, name="update"),
    path("profile/", views.profile, name="profile"),
    path("password/", views.change_password, name="change_password"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
]

restaurants/urls.py
from django.urls import path
from . import views

app_name = "restaurants"

urlpatterns = [
    path("", views.main, name="main"),
    path("index/", views.index, name="index"),
    path("menu/", views.menu, name="menu"),
    path("create/", views.create, name="create"),
    path("<int:restaurant_pk>/detail/", views.detail, name="detail"),
    path("<int:restaurant_pk>/update/", views.update, name="update"),
    path(
        "<int:restaurant_pk>/update/image_delete/",
        views.image_delete,
        name="image_delete",
    ),
    path("<int:restaurant_pk>/delete/", views.delete, name="delete"),
    path("<int:restaurant_pk>/like/", views.like, name="like"),
    path("search/", views.search, name="search"),
]

templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}{% endblock css %}
    {% block title %}{% endblock title %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="icon" href=" {% static 'images/dish.svg'%} ">
  </head>

  <body>
    <!-- 네비게이션바 -->
    <nav style="background-color: #fc6;" class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'restaurants:main' %}">
          <img src="{% static 'images/2.svg' %}" style="width: 44px; height:40px;" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between d-flex" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'restaurants:index' %}">음식점목록</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'restaurants:create' %}">음식점 정보등록</a>
            </li>
            <!-- 어드민만 보이는 회원목록 -->
            {% if request.user.is_superuser == 1 %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:index' %}">회원정보 목록</a>
              </li>
            {% endif %}
          </ul>

          {% if request.user.is_authenticated %}
            <div class="navbar-nav d-flex">
              <p class="nav-link mb-0 fw-bold">
                {% if request.user.image %}
                  <img src="{{ request.user.image.url }}" alt="" style="width: 30px; height: 28px; border-radius: 500px">
                {% endif %}
                <a href="{% url 'accounts:detail' request.user.pk %}" class="link-light">{{ request.user }}님 안녕하세요!</a>
              </p>
              <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
            </div>
          {% else %}
            <div class="navbar-nav d-flex">
              <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
              <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </div>
          {% endif %}
          <form class="d-flex" action="{% url 'restaurants:search' %}">
            <input style="width: 150px; border: 0.1rem solid #cdcdcd; border-radius: 5rem;" class="px-3" type="search" name="search" placeholder="검색" aria-label="Search" required="required">
            <button style="background-color: #fc6" class="border border-0">
              <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="click" style="width:32px;height:32px" type="submit"></lord-icon>
            </button>
          </form>
        </div>
      </div>
    </nav>

    <!-- 메시지 출력 -->
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}

    <!-- 메인 내용 -->
    <main class="container">
      {% block content %}{% endblock content %}
    </main>

    <!-- 푸터 -->
    <footer class="sticky-bottom my-5">
      <div class="card">
        <div class="card-body text-center">
          made by. 유영, 서림, 성인, 윤식
        </div>
      </div>
    </footer>

    <!-- 스크립트 -->
    {% bootstrap_javascript %}
    <script src="https://cdn.lordicon.com/qjzruarw.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    {% block js %}{% endblock js %}
  </body>

</html>